### ISSUE TITLE
getcreds.sh receives a 404 when requesting trainings.csv

### ISSUE THREAD

**Issue by jweyrich** [pridkett/watson-in-30-minutes#2]
$ ./getcreds.sh 
Fetching Credentials...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   293    0   293    0     0    181      0 --:--:--  0:00:01 --:--:--   181
Credentials saved to credentials.json
Fetching Training Data...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30    0    30    0     0     26      0 --:--:--  0:00:01 --:--:--    26
Training data saved to training.csv

$ cat training.csv 
Cannot GET /data/training.csv

**Comment by pridkett** [comment]
fixed

**Comment by jweyrich** [comment]
Thank you! Nice demo btw! :-)
